<a href="https://colab.research.google.com/github/Greeshu-09/AISECT-AIML/blob/main/RFE_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
import pickle
import matplotlib.pyplot as plt

In [19]:
dataset=pd.read_csv("/content/Iris.csv")

In [20]:
dataset

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [21]:
  dataset.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [35]:
x=dataset[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y=[[ 'Species']]

In [23]:
def split_scalar(X,Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)

In [24]:
#creating function from classification metrics as a performance metric
def classification_metrics(classifier, X_test, y_test):
    # Predictions
    y_pred = classifier.predict(X_test)

    # Import metrics
    from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')  # use 'binary' for binary problems
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)

    # Optional: classification report
    report = classification_report(y_test, y_pred)

    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1_score': f1,
        'confusion_matrix': cm,
        'classification_report': report
    }


In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

def train_and_evaluate_decision_tree(X, y):
    """
    Trains a Decision Tree classifier, evaluates its performance, and returns metrics.

    Args:
        X: Features (DataFrame).
        y: Target (Series or DataFrame).

    Returns:
        A dictionary containing accuracy, precision, recall, f1_score, and confusion_matrix.
    """
    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # Initialize and train the Decision Tree classifier
    dt_classifier = DecisionTreeClassifier(random_state=42)
    dt_classifier.fit(X_train, y_train)

    # Evaluate the classifier using the existing classification_metrics function
    metrics = classification_metrics(dt_classifier, X_test, y_test)

    return metrics

In [27]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

def train_and_evaluate_svm(X, y):
    """
    Trains an SVM classifier, evaluates its performance, and returns metrics.

    Args:
        X: Features (DataFrame).
        y: Target (Series or DataFrame).

    Returns:
        A dictionary containing accuracy, precision, recall, f1_score, and confusion_matrix.
    """
    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # Initialize and train the SVM classifier
    svm_classifier = SVC(random_state=42)
    svm_classifier.fit(X_train, y_train)

    # Evaluate the classifier using the existing classification_metrics function
    metrics = classification_metrics(svm_classifier, X_test, y_test)

    return metrics

In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

def train_and_evaluate_random_forest(X, y):
    """
    Trains a Random Forest classifier, evaluates its performance, and returns metrics.

    Args:
        X: Features (DataFrame).
        y: Target (Series or DataFrame).

    Returns:
        A dictionary containing accuracy, precision, recall, f1_score, and confusion_matrix.
    """
    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # Initialize and train the Random Forest classifier
    rf_classifier = RandomForestClassifier(random_state=42)
    rf_classifier.fit(X_train, y_train)

    # Evaluate the classifier using the existing classification_metrics function
    metrics = classification_metrics(rf_classifier, X_test, y_test)

    return metrics

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

def train_and_evaluate_logistic_regression(X, y):
    """
    Trains a Logistic Regression classifier, evaluates its performance, and returns metrics.

    Args:
        X: Features (DataFrame).
        y: Target (Series or DataFrame).

    Returns:
        A dictionary containing accuracy, precision, recall, f1_score, and confusion_matrix.
    """
    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # Initialize and train the Logistic Regression classifier
    lr_classifier = LogisticRegression(random_state=42, solver='liblinear') # Added solver for clarity
    lr_classifier.fit(X_train, y_train)

    # Evaluate the classifier using the existing classification_metrics function
    metrics = classification_metrics(lr_classifier, X_test, y_test)

    return metrics

In [30]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

def train_and_evaluate_knn(X, y):
    """
    Trains a KNN classifier, evaluates its performance, and returns metrics.

    Args:
        X: Features (DataFrame).
        y: Target (Series or DataFrame).

    Returns:
        A dictionary containing accuracy, precision, recall, f1_score, and confusion_matrix.
    """
    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # Initialize and train the KNN classifier
    knn_classifier = KNeighborsClassifier()
    knn_classifier.fit(X_train, y_train)

    # Evaluate the classifier using the existing classification_metrics function
    metrics = classification_metrics(knn_classifier, X_test, y_test)

    return metrics

In [39]:
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split # Ensure train_test_split is imported here

def evaluate_models_with_rfe(X, y, n):
    """
    Applies RFE with various classifiers to select top features and evaluates models.

    Args:
        X: Features (DataFrame).
        y: Target (Series or DataFrame).
        n: The number of features to select.

    Returns:
        A dictionary where keys are model names and values are a dictionary containing their performance metrics and selected features.
    """
    results = {}

    # Define classifiers to use with RFE
    # Removed KNN as it is not compatible with RFE
    classifiers = {
        "Decision Tree": DecisionTreeClassifier(random_state=42),
        "SVM": SVC(random_state=42, kernel="linear"), # Using linear kernel for RFE
        "Logistic Regression": LogisticRegression(random_state=42, solver='liblinear'),
        "Random Forest": RandomForestClassifier(random_state=42),
        # "KNN": KNeighborsClassifier() # KNN removed
    }

    # Define classifiers to evaluate without RFE (if needed, or handle separately)
    # For now, focusing on RFE compatible models as per the function's purpose

    for name, classifier in classifiers.items():
        print(f"Evaluating {name} with RFE...")

        # Initialize RFE
        rfe = RFE(estimator=classifier, n_features_to_select=n)

        # Fit RFE
        rfe.fit(X, y)

        # Get the selected features
        selected_features = X.columns[rfe.support_].tolist()

        # Split data into training and testing sets using selected features
        X_selected = X[selected_features]
        X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.3, random_state=42)


        # Train the classifier on the selected features
        model = classifier
        model.fit(X_train, y_train)

        # Evaluate the classifier
        metrics = classification_metrics(model, X_test, y_test)
        results[name] = {'metrics': metrics, 'selected_features': selected_features}
        print(f"{name} Evaluation Complete.\n")

    return results

In [41]:
# Assuming you want to select 2 features, you can change this number
n_features = 2

# Run the RFE and evaluation function
rfe_results = evaluate_models_with_rfe(x, y, n_features)

# Print the results for each model in a similar format to the user's request
for model_name, result_data in rfe_results.items():
    print(f"Model: {model_name}")
    print("Selected Columns:", result_data['selected_features'])
    # Printing Accuracy as the primary metric, similar to R2 in the example format
    # print(f"Accuracy: {result_data['metrics']['accuracy']:.4f}\n")
    # Print other classification metrics
    print(f"Precision: {result_data['metrics']['precision']:.4f}")
    print(f"Recall: {result_data['metrics']['recall']:.4f}")
    print(f"F1-Score: {result_data['metrics']['f1_score']:.4f}")
    print(f"Confusion Matrix:\n{result_data['metrics']['confusion_matrix']}\n")

Evaluating Decision Tree with RFE...
Decision Tree Evaluation Complete.

Evaluating SVM with RFE...
SVM Evaluation Complete.

Evaluating Logistic Regression with RFE...
Logistic Regression Evaluation Complete.

Evaluating Random Forest with RFE...
Random Forest Evaluation Complete.

Model: Decision Tree
Selected Columns: ['PetalLengthCm', 'PetalWidthCm']
Precision: 1.0000
Recall: 1.0000
F1-Score: 1.0000
Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Model: SVM
Selected Columns: ['PetalLengthCm', 'PetalWidthCm']
Precision: 1.0000
Recall: 1.0000
F1-Score: 1.0000
Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Model: Logistic Regression
Selected Columns: ['SepalWidthCm', 'PetalWidthCm']
Precision: 0.9320
Recall: 0.9111
F1-Score: 0.9090
Confusion Matrix:
[[19  0  0]
 [ 0  9  4]
 [ 0  0 13]]

Model: Random Forest
Selected Columns: ['PetalLengthCm', 'PetalWidthCm']
Precision: 1.0000
Recall: 1.0000
F1-Score: 1.0000
Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

